### ISSUE TITLE
Reject saving stale form data

### ISSUE THREAD

**Issue by cavis** [PRX/feeder.prx.org#1000]
So for the case:

1. User A and User B load an episode form
2. User A publishes episode
3. User B edits the title and saves

Now the episode is _unpublished_ again, with the new title from 3.  This kind of conflict could really happen on any objects/fields.

We should handle with optimistic locking... the changes in (3) should be rejected.  Rails/ActiveRecord has some built-ins for this, if you add a column.  Or DIY it with updated_at?

Then we have some decisions after (3).  What error message does User B get?  Are their changes still in the unsaved-form?  Can they opt to overwrite User A by clicking save a second time?

**Comment by kookster** [comment]
I'd probably try rails optimistic locking

https://api.rubyonrails.org/classes/ActiveRecord/Locking/Optimistic.html

**Comment by cavis** [comment]
Yep, that's the "add a column" option.  Though I do wonder if you could just wire that into the updated_at epoch.
