### ISSUE TITLE
Add human readable episode identifier for adzerk keyword

### ISSUE THREAD

**Issue by kookster** [PRX/feeder.prx.org#102]
We don't know if the keyword can contain spaces, special characters, etc.
We also don't know how long it can be.
We do want to add an episode specific keyword, which could be a sanitized version of the title (persisted even if the title changes) or sanitized original GUID.

**Comment by kookster** [comment]
http://dev.adzerk.com/docs/keyword-targeting
http://dev.adzerk.com/docs/keyword-targeting#section-reporting-on-keywords

**Comment by gcampo88** [comment]
per @kookster : 
We do reporting in adzerk for what ads get served, and we're really good 
at reporting on what ads were served in what timeframe, on what feed. What we 
don't do well is report on which episode those ads were served on.
For example, wanting to know how many and what ads were served on the latest episode. 
To do that reporting better, we ought to have an episode identifier as 
one of the values you can filter a report on. So, this ticket is to come up with a good, 
human readable identifier which will uniquely identify an episode for that reporting

Considerations: 

- one is making it unique to the episode
- two is human readable 
- and I guess three is making sure it is a value adzerk can handle
- 

The flow here is that the feeder api will provide it on the episode representer.
So dovetail will call feeder api for an episode by guid, in the resource that comes 
back will be this identifier, and dovetail will pass that along as a 'keyword' to adzerk.
b/c that's one of the customizable things we can pass along to adzerk
http://dev.adzerk.com/docs/keyword-targeting
http://dev.adzerk.com/docs/keyword-targeting#section-reporting-on-keywords
Info + rules about keywords + formatting in links above.

Note, the max for all keywords on a request is 512, but that is for all keywords, not 
just this id, so we probably want to keep it shorter than that, both to make it easier to read, 
and leave space for more. We're mostly planning to use this keyword for reporting, not so much for 
targeting. So the human readable part is key, so it is easy to use in the reports

Maybe some combo of part of the title + part of the guid + part of the published_at. 
To make sure these values are unique, and also don't change, may need to "freeze" 
the value in its own column, even if it is derived from several.
