### ISSUE TITLE
Episode segmenter labels incorrect for shows with an "intro" segment

### ISSUE THREAD

**Issue by cavis** [PRX/feeder.prx.org#1057]
Some shows that have an "Intro" original segment in Augury:

![image](https://github.com/user-attachments/assets/c0e41fdd-0f09-4153-ad54-5ebe6a2ec069)

But when segmenting your audio in Feeder, the labels are a bit misleading:

![image](https://github.com/user-attachments/assets/a89752d9-7c0d-4a34-8e46-cd1697ca5623)

Bad idea: make the labels very generic?  "Break 1/2/3" and "Trim start" / "Trim end"?

**Comment by brandonhundt** [comment]
+1 calling them "Breaks"
