### ISSUE TITLE
Delegated delivery validates the podcast and podcast episodes

### ISSUE THREAD

**Issue by svevang** [PRX/feeder.prx.org#1088]
to add to this - 
- When a podcast enables apple feed / delegated delivery, warn the show that the feed has to match Apple's rules
- Validate the data in the episodes by these more restrictive policies when changing/saving data
- For older data, truncate the data in the API calls to Apple and in the RSS feed

**Comment by kookster** [comment]
fwiw - rails has a trunctae method that should work for this? 
https://api.rubyonrails.org/classes/String.html#method-i-truncate_bytes

**Comment by kookster** [comment]
@svevang did you mean to close this?

**Comment by svevang** [comment]
Yep!  There's cyclical dependencies between apples validations and ours (since RSS exists, but typically sync blocks the update of RSS). If we adopt conditional validations in this way that is potentially more work than solving the validations at the top level. Was thinking that we should at least look at the requirements around the top level before embarking on a conditional validation scheme.

Ideally, we create an epoch style ticket with the reqs, look through those and if it seems possible we can solve this at the Episode level validations. Plus there is another option for those episodes with novellas in their description: truncate and link to the expanded description?  Would be good to look through the requirements and see what makes sense!

**Comment by kookster** [comment]
Do we have a different ticket for your suggestions above?
If not, instead of closing, can we change the description of this ticket, since it addresses the same problem?

We already have in place validations at 4k for description, I don't think a link to the rest is needed for the legacy data that got through before we had that in place.

**Comment by svevang** [comment]
Created a new issue here: https://github.com/PRX/feeder.prx.org/issues/1090
