### ISSUE TITLE
Transcript last updated at

### ISSUE THREAD

**Issue by kookster** [PRX/feeder.prx.org#1128]
Noting that the last updated at on the episode transcript page does not reflect the updated_at time on the transcript entry in the db.

When I updated the `format` for a transcript, the last saved time did not updated - looks like it is using the episode updated_at, not the transcript:

```
<p class="status-text mt-2 mb-0 text-end"><strong><%= t(".updated_at_hint") %>:</strong> <%= l(episode.updated_at) %></p>
```
https://github.com/PRX/feeder.prx.org/blob/main/app/views/episode_transcripts/_form_status.html.erb#L15

Also the episode saved at date is an abbreviated format that differs from this page. These should be consistent, on the episode it uses `local_time_ago` to format the date:
https://github.com/PRX/feeder.prx.org/blob/07e3b468d36e8d6a6e49f3c65d8bb00eb34039c0/app/views/episodes/_form_status.html.erb#L56

**Comment by cavis** [comment]
Yeah, we should probably use the actual `transcript.updated_at` for this.  But additionally:

- [ ] Transcripts should be `touch: true`-ing their episode when they save.  Our cache strategies require those timestamps to bubble up.
- [ ] We should similarly fix the Media Files tab for these same issues
