### ISSUE TITLE
itunes:explicit incorrect for Bugle

### ISSUE THREAD

**Issue by debenedictis** [PRX/feeder.prx.org#142]
In the Wordpress source feed itunes:explicit has the value "yes" (see line 26).
But, in the Dovetail feed the value is "false" (see line 28).

According to [this link](https://help.apple.com/itc/podcasts_connect/#/itcb54353390), valid values for <iTunes:explicit> are: "Yes | Explicit | True" or "Clean | No | False".

**Comment by kookster** [comment]
fixed, but need to see why this wasn't copied over correctly.
