### ISSUE TITLE
itunes:new-feed-url not being copied to DT feed

### ISSUE THREAD

**Issue by debenedictis** [PRX/feeder.prx.org#144]
Line 42 of the TMP raw feed has the itunes:new-feed-url tag:

    <itunes:new-feed-url>http://feeds.thememorypalace.us/thememorypalace</itunes:new-feed-url>

The corresponding DT feed does not have the itunes:new-feed-url tag.

I believe this is also the case for Bugle, and perhaps others.

**Comment by kookster** [comment]
will need fixes to crier and feeder:
- [ ] crier: https://github.com/PRX/crier.prx.org/pull/52
- [ ] feeder: TBD
