### ISSUE TITLE
Unable to get rid of itunesCategories

### ISSUE THREAD

**Issue by kookster** [PRX/feeder.prx.org#159]
@cavis can you describe with more detail?

**Comment by cavis** [comment]
When I PUT an empty `itunesCategories: []` or `itunesCategories: null`, it doesn't actually update the category.  Need some way to set it back to blank (presumably with the element not even showing up in the rss).

**Comment by kookster** [comment]
ok, further info makes it seem like this works, but isn't touching the parent podcast to break the cache
