### ISSUE TITLE
Broken links to CMS images/audio

### ISSUE THREAD

**Issue by cavis** [PRX/feeder.prx.org#177]
In feeder-staging rendered feeds:

Seeing an issue where image (and audio) assets from CMS are relative rather than absolute.  Need to make sure these all come out `https://cms-staging.prx.tech/the/relative/path`.

**Comment by kookster** [comment]
@cavis Is there an example of this? trying to see what is still broken

**Comment by kookster** [comment]
I believe this is fixed now with the update to DOVETAIL_HOST and cms change to always use full path urls for assets.
