### ISSUE TITLE
Item appearing in feed before audio is available

### ISSUE THREAD

**Issue by cavis** [PRX/feeder.prx.org#178]
In feeder-staging, via CMS/publish.

1. Create a new story in Publish (in a series setup as a podcast)
2. Go look at `http://feeder-staging.prx.tech/podcasts/1234` and keep refreshing
3. The `<item>` shows up immediately, but with no audio enclosure
4. 30-60 seconds later, the audio enclosure shows up

Feed `<item>`s should not be shown until both the audio and image assets have been processed.

**Comment by kookster** [comment]
fixed by #186
