### ISSUE TITLE
Refactor enclosures on an episode

### ISSUE THREAD

**Issue by kookster** [PRX/feeder.prx.org#193]
There's alot of duplication in the code to support enclosures and contents.
Pretty sure it could be refactored to just have the list of mediafiles, with enclosures having a subset of of the attributes that media:contents do, and treat an enclosure as just a single media file on an episode, and media:contents as multiple.

This is especially true with the enclosure url for an episode as a single url regardless of the underlying number of actual media files, enabled by assuming that the url will be satisfied by dovetail providing any stitching necessary.

**Comment by cavis** [comment]
Enclosure (the model) is gone.  Fixed!
