### ISSUE TITLE
item tag/category not updating

### ISSUE THREAD

**Issue by sandikbarr** [PRX/feeder.prx.org#218]
When changes are made to an item's tags (just update the tags field), those updates are not reflected in the feed.

**Comment by kookster** [comment]
I did many changes to the tags on this story, and they all came through, so I'm not sure there is anything to fix here - https://publish-staging.prx.tech/story/187155

Perhaps there is a more general problem of announced story updates not saving to feeder episodes sometimes?

**Comment by sandikbarr** [comment]
Possibly some other issue, but not reproducible with an update to tags, so I'd vote for closing this
