### ISSUE TITLE
Updated episode briefly visible with no-audio

### ISSUE THREAD

**Issue by cavis** [PRX/feeder.prx.org#236]
Seeing some brief "feeder episode has no audio" errors in dovetail.

Appears to happen when an episode of the moth is updated or re-published.  The episode is then visible, but with an empty audio array.  Then a bit later, the audio shows up.  Presumably because it was waiting for fixer to process it.

Need to make sure we always have some audio to show for a visible episode.  (Or worst case - 404 it).

**Comment by gcampo88** [comment]
The "visible episode with no audio" happens a lot in the imports of existing podcast audio to CMS & Feeder (though doesn't show up as Dovetail errors because the addition to dovetail comes later in the import process). So... bump!

**Comment by cavis** [comment]
Been a minute since I've seen this - closing!
