### ISSUE TITLE
Podcasts/episodes not cleaned up when CMS deletes them

### ISSUE THREAD

**Issue by cavis** [PRX/feeder.prx.org#242]
Not sure where this will need to be fixed, but bad data is remaining in Feeder.

Bug:

1. Create/publish a podcast and episode via Publish
2. Wait for it to show up in Feeder
3. Delete episode and podcast in Publish
4. Result: CMS hard-deletes the Series, but Feeder doesn't get the change at all.  (May also be a problem in Episode handling, but didn't get that far yet).

**Comment by gcampo88** [comment]
Fixed now in staging after a couple CMS PRs (https://github.com/PRX/cms.prx.org/pull/321 and https://github.com/PRX/cms.prx.org/pull/320)

**Comment by kookster** [comment]
fixed, closing
