### ISSUE TITLE
Not retrying fixer callback failures

### ISSUE THREAD

**Issue by kookster** [PRX/feeder.prx.org#248]
When there is an issue with a fixer callback, such as a problem getting a db connection, it doesn't seem to retry, or if it does it is far from timely.

**Comment by pkarman** [comment]
Related to #249?
Scoring as similar.

**Comment by cavis** [comment]
No longer seems to be an issue, with Porter

**Comment by karpet** [comment]
hooray for GH issue cleanup! ;)
