### ISSUE TITLE
Make shoryuken concurrency count an environment variable

### ISSUE THREAD

**Issue by gcampo88** [PRX/feeder.prx.org#265]
Instead of hardcoding it
https://github.com/PRX/feeder.prx.org/blob/master/config/shoryuken.yml#L8

goes with https://github.com/PRX/cms.prx.org/issues/373

**Comment by kookster** [comment]
I needed to do this for testing imports locally, so adding to the milestone

**Comment by gcampo88** [comment]
i think this is done with https://github.com/PRX/feeder.prx.org/pull/271/files
