### ISSUE TITLE
Add caching

### ISSUE THREAD

**Issue by gcampo88** [PRX/feeder.prx.org#275]
pasting slack conversation on the topic below: 

Ryan Cavis [11:09 AM] 
i think we’re just using the rails memory cache
which isn’t great, for our ECS setup anyways

Andrew Kuklewicz [11:10 AM] 
it manages to provide ~20ms responses to all those dovetail requests, but when overwhelmed by 120s requests for an enormous rss feed, it got swamped (edited)
an nginx or other cache in front could help

Ryan Cavis [11:10 AM] 
yeah, and backsaw is asking for `api/v1/podcast?per=1000` or something

Andrew Kuklewicz [11:11 AM] 
(which will generally break the cache anyway)

Ryan Cavis [11:12 AM] 
so what if … instead of adding nginx, we just memcached everything, and did a TTL-cache on the feed rss, so it doesn’t refresh with every little change?
i guess dovetail requests might get slightly slower

Andrew Kuklewicz [11:14 AM] 
so fixer would still be hitting the feed, but now it would have a ttl page cache on it?

Ryan Cavis [11:14 AM] 
yeah.  or depending on how complex you want to get, do some sort of “debouncing” on breaking that page cache.
so single-updates will break the cache right away, but tons of them coming in at once won’t

[11:44] 
while i'm revealing my ignorance on these CS fundamentals... we have our db pool size set to 10 and our worker thread count set to 10. would that mean that there's no db connection left for anything that's not the import, during a mega import like this?

Andrew Kuklewicz [11:59 AM] 
no decisions yet, but agreed, happy to have that worked shared

**Comment by cavis** [comment]
So I'm assuming the requirements here are:

- [ ] Benchmark, and consider switching over to, a shared memcached
  - Make sure DT episode response times remain quick
- [ ] Set a TTL-based page cache on the feed rss
  - Or maybe also break this cache when an episode updates?  Or that may throw us back into the overwhelmed-by-fixer boat.

**Comment by cavis** [comment]
Redis caching exists!
