### ISSUE TITLE
After Podcast Import there is a lag of about 5 minutes before podcast is ready in feeder

### ISSUE THREAD

**Issue by svevang** [PRX/feeder.prx.org#307]
After the podcast import succeeds and the podcast is unlocked in feeder, there is a ~5 minute lag before all the media and episodes are ready in the feeder RSS.  

UX problem: What signal can we use so that people know about what's happening with the feeder process (a.k.a why are some of my episodes missing).

This could also cause gratuitous writes to the feeder RSS caching scheme. If we could synchronize the unlocking with the convergence of async processes, we could eliminate potential thrashing.

**Comment by cavis** [comment]
No longer an issue, with the new Feeder UI.  CMS imports going away, so calling this good.
