### ISSUE TITLE
Multiple Feeds

### ISSUE THREAD

**Issue by brandonhundt** [PRX/feeder.prx.org#387]
Design: https://github.com/PRX/publish.prx.org/issues/748

- Each series gets a public feed by default
- Each sub feed can override the settings of the main feed
- Audio enclosure type needs to be its own feature.

Questions remain:
- Windowing (passing the date offset through Augury)
- If the implementation of this page becomes challenging or javascript fights it, we are open to suggestions. One save button to rule them all is problematic. 

Out of scope:
- Personal auth tokens

**Comment by kookster** [comment]
yeah, thinking about this, how to implement:
### Enhance feeder to have `Feed` model, which describes additional feeds for a Podcast.
  * Generate a token to use in the path, essentially the guid for this feed
  * Specify which types of placements are allowed: 
    * Ad free (no paid ads, include house and sonic ids)
    * Original only (no house ads or Sonic IDs either)
  * Include in the API for the podcast, listing the feeds and their urls
    * This has to be a private API call now, so folks can't just discover ad free feeds
  * Specify which episodes appear
    * Max episodes on the feed (does it include the full archive)
    * Delay episodes (put only the latest in some feeds, delay/window release others)
    * Category filter - make a feed for only a single category/keyword
      * Could use this for sub feed like AOI or Book Exploder?
  * Specify audio type in the enclosures
    * Thinking about Apple and providing higher quality audio
