### ISSUE TITLE
Generate multiple RSS feeds

### ISSUE THREAD

**Issue by cavis** [PRX/feeder.prx.org#402]
Given the new `feeds` table/model:

- [ ] For each feed, generate an RSS file
- [ ] Default feeds in S3 subfolder at `#{feed.file_name}`
- [ ] Non-default feeds in S3 subfolder at `#{feed.slug}/#{feed.file_name}`
- [ ] Non-default feeds get an enclosure that includes the feed-slug
- [ ] Use the various feed settings (title, episode/full-episode counts, publish offset, keyword filter)
- [ ] May need each feed to have a custom `enclosure_prefix` sooner than i thought (to remove feedburner).  Maybe?

**Comment by Mstandastote** [comment]
HTML simple text format all data

**Comment by kookster** [comment]
multiple feeds released
