### ISSUE TITLE
Unique RSS feed urls for major distribution options

### ISSUE THREAD

**Issue by driki** [PRX/feeder.prx.org#42]
Not sure if this ends up in feeder? but we should submit unique URLs for shows to Spotify, iTunes, Stitcher and other listening services that require submission to be added. This will allow us to better control the episodes that appear within those listening options.

**Comment by gcampo88** [comment]
Do we still want this?

**Comment by kookster** [comment]
the need is still there for some, like spotify, that cache episodes.
however, they are still not a substantial enough % of playback to make this a priority.

There are a number of tickets ideas where having different versions of the feed, perhaps even for each user, would be a useful trick, so I would like to keep this around, but low priority.

We may take up a proxy/caching service for feeds which could enable some of these tricks.

**Comment by cavis** [comment]
We have multiple feeds now - closing.
