### ISSUE TITLE
RFC: How do we want to maintain audio templates in a Feeder frontend?

### ISSUE THREAD

**Issue by brandonhundt** [PRX/feeder.prx.org#437]
As we move away from Publish to Feeder, what are the changes we want to make to audio templates?

**Comment by cavis** [comment]
RFC: we don't!

**Comment by cavis** [comment]
Per [this slack thread](https://prx.slack.com/archives/G0FKLK2Q5/p1663692218415549) ...

We already have an `episode.num_segments` field.  Could add that to the planner and episode-form.

And we can assume Feeder can (A) check if a show is setup in Augury or not, and (B) check/show the Placement for this num-originals.
