### ISSUE TITLE
Research: splitting audio files UI

### ISSUE THREAD

**Issue by cavis** [PRX/feeder.prx.org#472]
Do some research/planning on how we'll split a single uploaded audio file into multiple segments.

Should handle mp3/wav/flac at least.  (Right?)

Maybe https://wavesurfer-js.org/projects/ ?

Can the browser split the audio file in-memory and upload the resulting segments to Feeder?  Or do we need to build out a schema/worker in Feeder to supporting uploading 1 big file then "split to these timestamps"?

**Comment by kookster** [comment]
https://github.com/bbc/peaks.js
is another
