### ISSUE TITLE
Apple now lets you choose more <itunes_category> than previously allowed

### ISSUE THREAD

**Issue by brandonhundt** [PRX/feeder.prx.org#556]
Currently, we allow one category to be selected in the frontend. Apple is now allowing up to 4 to be selected -- 2 Top level, each with its own sub category. We should keep up to date with Apple's changes on this front. 

See this thread for much more detail and discussion: https://prx.slack.com/archives/G0FKLK2Q5/p1675282674372299

**Comment by kookster** [comment]
current publish allows 2 (1 top level, 1 sub:


![Image](https://user-images.githubusercontent.com/46439/217028721-6d3b9bd3-95c0-4b21-b7d6-dfbdb39c6016.png)

would be good to have 2 top level, each with a sub

**Comment by cavis** [comment]
This came up with the RSS importer, so closing this in favor of #890.
