### ISSUE TITLE
Figure out domains

### ISSUE THREAD

**Issue by farski** [PRX/feeder.prx.org#566]
I think we should do some thinking about how our domains for Feeder/Publish/Metrics shake out after this rebuild. Feeder, to me, isn't a very good consumer-facing brand.

**Comment by kookster** [comment]
Probably a meeting to discuss, with @brandonhundt once he's back, I'll assign to him for now, and put out a couple of sprints

**Comment by kookster** [comment]
A few thoughts, which I do not feel strongly about - 
 - The product as a whole is dovetail, and I think we want to market it and talk about it that way
 - We currently expose the apps (publish, metrics, augury) via ID, and that should be rethought as well as the subdomains
 - We could treat this as apps within Dovetail, and expose that - perhaps namespace them in ID so it is clear they are all parts of Dovetail
 - We could, as suggested in preening, reclaim dovetail.prx.org from being a marketing only site
 - At least a link to login on dovetail.prx.org for existing users makes sense, or like www.prx.org, show you are logged in and link to profile/apps you can acess
 - I am less concerned with the domains used for parts of dovetail while logged in, and more concerned about how they are named and presented on links, docs, navigation to the users. Many apps like salesforce use a variety of unfriendly subdomain and host names after a user is logged in.

**Comment by brandonhundt** [comment]
I think I can respond generally by saying that Dovetail is the Product and the brand. It contains many many apps. The apps should not be branded individually.

The navigation we are applying to feeder takes this into account. We are already papering over feeder name by calling it "Podcasts". We should not think of "Podcasts" as its own product though, but a section of Dovetail. augury is papered over as "Inventory". Metrics, it may still be called Metrics, but Metrics is a section of Dovetail and maybe a section within "Podcasts" 

Here's my flare on this based on the assumption that prx.org remains the base domain name. 

- I'd be very uncomfortable moving the DT marketing site off of dovetail.prx.org, but I agree that we should add a login link to the marketing site. I can write a ticket. The link should go to id.prx.org
- I think if we applied the a similar Nav to ID it would be helpful. (I understand ID is NOT Dovetail but the route to get to Dovetail specific apps). We should also think about how Dovetail access is represented within ID a little as that is a major point where the App names appear in the Frontend.
- `feeder.dovetail.prx.org` feels clunky, but I think its workable. Again if folks are mainly accessing the site through the login link or a bookmark, it might be okay.
- `feeder.prx.org` could also be left alone as long as the nav is updated through all Dovetail apps.
- Any thoughts on `dovetail.prx.org/app/app-name`? Or is that too mono-repoish? Example: `dovetail.prx.org/app/feeder` `dovetail.prx.org/app/augury`
- Should we rename feeder and augury to less meaningful, more mundane things? `inventory.prx.org` etc.

And is there the possibility we move Dovetail off of the PRX base domain and move it to its own??? Then we could use one level of subdomains. Finding a domain may be tricky. `dovetailapp.org` `getdovetail.org` `dovetailprx.org`, `https://doveta.il` etc

I think its worth a discussion!

**Comment by farski** [comment]
What's an example of Dovetail being used as a brand outside of the product?

**Comment by farski** [comment]
In all those cases, though, it seems like the Dovetail product is still the thing being discussed. Or I'm not familiar with what, for example, is being discussed with CPB under the Dovetail umbrella other than the app. Like what else exists under the brand umbrella other than the app?

For example, Coke is the brand name of a product (a drink) and also a brand (merch, events, physical locations, etc).

I'm not up to speed on how we use Dovetail to mean anything other than the product brand name that is a podcast hosting platform. I understand that the platform may be comprised of various apps, services, subdomains and other technical aspects behind the scenes.

I'm not pushing back, just trying to understand. Product/platform vs. individual app makes sense to me, but brand vs. product I'm still hazy on.

**Comment by brandonhundt** [comment]
Coming back to this. Escalating the priority to High to solve for the Feeder rollout.

Plan:
1. Settle on a name [see this doc](https://docs.google.com/document/d/1uJvhDvxISmQTbdIiBG9Zvd11bW9qxij50zyGJGZzz-A/edit). Goal of emphasizing Dovetail to avoid naming confusion. Feel free to provide your thoughts in the doc!! 
2. Write additional tickets
