### ISSUE TITLE
Validate episode `description` is present on podcast RSS

### ISSUE THREAD

**Issue by svevang** [PRX/feeder.prx.org#589]
The `description` field is required for Apple API episode create. Non-blank and Non-null.

Make sure that the RSS has a default value for each episode:

- [ ] helper to validate the presence of the description field
- [ ] provide a default description value for the RSS description field

**Comment by kookster** [comment]
I think we more generally need to look at bringing over validations from CMS -> Feeder models

**Comment by cavis** [comment]
Just noting from our last discussion: Publish doesn't require description at the moment.  And (I think) the CMS RSS-Importer also doesn't require it.  So we either need to add validations/data-migrations there first, or wait until CMS/Publish are deprecated.  Then we can add whatever we want to Feeder validations.

**Comment by cavis** [comment]
We have fallbacks for description now - so calling this good.
