### ISSUE TITLE
Implement status box Apple Feeds enhancements

### ISSUE THREAD

**Issue by brandonhundt** [PRX/feeder.prx.org#797]
A while back we had talked about producers having the ability to select which feed an episode should be published into. I still think this is a good idea. This way the producer then has full control over which episodes end up in which feeds, without having to rely on Keyword magic. 

If the Apple Subscriptions Feed is selected AND the episode is published, we can display an Apple Status of either Syncing, Retrying, or Complete

If a show ONLY has a "default feed" - we don't need to display this field.

related to #796 

![Publish Box](https://github.com/PRX/feeder.prx.org/assets/369739/bf74d4fb-450d-4652-919c-4e8ecc3c6ffd)

**Comment by cavis** [comment]
I think this is #632 ?

**Comment by brandonhundt** [comment]
Yes, I'll close this in favor of #632
