### ISSUE TITLE
Question: Is there a way to limit the time between publish of sub audio to Apple, and public audio in the feed?

### ISSUE THREAD

**Issue by kookster** [PRX/feeder.prx.org#851]
"this is helpful, thank you. do you have a sense from the other shows that have migrated to delegated delivery about what the window tends to be? there is discomfort from the [producer[ side with non-paying subscribers first seeing episodes as subscriber-only — I know that there’s not a way around it but would be helpful to know what that window looks like normally"

Is there a way to time how things are published that could reduce this period where the subscriber edition is published, but the public episode is not?

**Comment by cavis** [comment]
Could we push the episode meta/audio to the Apple API sooner, hour(s) ahead of the publish time?  If we set the Apple feed's `episode_offset_seconds` to something negative ... that should get picked up earlier.

Logically, that kind of makes sense.  This feed publishes episodes 1 hour ahead of the public feed.  But there are several gotchas:

1. I doubt the release_episodes logic would pick up on this - it works off the actual published_at, with no offset.
2. The episode wouldn't be in the Feeder API yet, so DTR would 404 you.  Unless you pass a JWT `?_t=` param?
3. I'd have to check, but DTR may not pick the correct ads for a not-published-yet episode.  Maybe less of an issue for these, which are generally remnant/baked-in house ads.

**Comment by cavis** [comment]
Okay, DTR does now support negative offsets.  And I've opened tickets for the rest of the stuff to fix on the Feeder side (the release_episodes cron, for one).

Calling this ticket good.
