### ISSUE TITLE
Escalate logging/alerts of publish failures?

### ISSUE THREAD

**Issue by kookster** [PRX/feeder.prx.org#876]
Wondering if we ought to have a louder failure when publishing an episode gets hung up?

Came up in the context of the description char limit, which prevented an episode from publishing for hours.

Maybe some clearer, more specific messaging about this, such that a distro team member could be aware and potentially investigate, like the delivery errors or swear word detector warnings?

**Comment by svevang** [comment]
Slack ops!

- Send message to the Slack re: publishing errors.

**Comment by cavis** [comment]
Whoops, I duped this in #1016.  Let's go with that one, since it has some specific numbers/reqs in it.
