### ISSUE TITLE
Slack notifications for new podcasts

### ISSUE THREAD

**Issue by kookster** [PRX/feeder.prx.org#917]
from Paloma:

> Hey team, when a podcast is created/imported using Publish, we get a notification in the [#support-data-monitoring](https://prx.slack.com/archives/CE9E6SSBW) channel. Can we get the same when a show is setup/imported in feeder?

**Comment by cavis** [comment]
Okay, here are some requirements:

- Add a controller concern/tooling for sending messages to slack (via the SNS relay).  See Exchange for prior art.
- In the `app/controllers/podcasts_controller.rb` ... after successfully creating a podcast, send a message to `#support-data-monitoring`
- Bonus points: make it look nice.  Include a link back to feeder.

I'm not sure we'll want/need to alert when PodcastImports are created?  So let's hold off on that for now, and just do this podcast-created alert.
