### ISSUE TITLE
ITunes Summary handling

### ISSUE THREAD

**Issue by cavis** [PRX/feeder.prx.org#949]
In the new Feeder UI, we decided not to include the itunes:summary field anymore.  Since it no longer appears [in the apple docs](https://help.apple.com/itc/podcasts_connect/#/itcb54353390).

But it turns out - Apple Podcasts is still using/preferring that field, over the description.  What to do?  Things to decide:

1. The PodcastRSSImporter still pulls in the summary - should we stop doing that?
2. For shows transitioning from Publish to Feeder UI, they won't be able to edit the existing summary.  Should we just nil the field out, when you save from the non-API controller?  Or what?
3. The RSS builder still falls back to sanitizing the description, to render the `<itunes:summary>` flag.  Should we stop doing that?

**Comment by cavis** [comment]
Todo: look at popular podcast RSS feeds, and see if they have itunes:summary tags.  If not, we can probably just drop the field.

**Comment by brandonhundt** [comment]
Darknet on Megaphone still has it too, but the content is the same, only with all `<a>` tags stripped

https://feeds.megaphone.fm/darknetdiaries

**Comment by brandonhundt** [comment]
Discussion here: https://prx.slack.com/archives/G0FKLK2Q5/p1705951262864649
